### PR TITLE
xenmgr: Add stubdom and init flask labels

### PR DESCRIPTION
**Pull request by jandryuk**
libxl supports two additional XSM FLask labels in a domain's
configuration.  One is used for the stubdom (device model).  The other
is a building label (init) distinct from the regular runtime label.
Transitioning from the building to runtime label allows dropping
permissions from the toolstack domain over the domain.

Pass through the stubdom and init labels to the xl config when present
in dbd.

Signed-off-by: Jason Andryuk <jandryuk@gmail.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6555

**Comment by jean-edouard** [comment]
@jandryuk am I doing something wrong?
```
root@xenclient-dom0:~# xec-vm -n w get flask-label
system_u:system_r:hvm_guest_t
root@xenclient-dom0:~# xec-vm -n w get init-flask-label
xec: property init-flask-label not found in any of the interfaces
root@xenclient-dom0:~# xec-vm -n w get stubdom-flask-label
xec: property stubdom-flask-label not found in any of the interfaces
```

**Comment by jandryuk** [comment]
No... I didn't wire up the DBus RPC interface to those.  I can do that.

xenmgr will read them out of dbd, so you can set them with `db-write /vm/$( xec-vm -n $vm get uuid )/config/stubdom-flask-label system_u:system_r:stubdom_t`.  I don't think we have a working `init-flask-label` in xen-xsm-policy, but you can set `stubdom-flask-label`.

**Comment by jean-edouard** [comment]
Yeah, please wire those up to dbus to match the other VM properties.
Thank you

**Comment by jandryuk** [comment]
Updated to expose new labels over DBus.  I rebased since the branch would not build against the updated idl.  I guess a merge into master would have built, but I only thought of that now.

Needs https://github.com/OpenXT/idl/pull/34

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6573

**Comment by jean-edouard** [comment]
LGTM, merging soon.

**Pull request merged**
