### PR TITLE
OXT-1384: Syncvm Flask label

### PR DESCRIPTION
**Pull request by jandryuk**
The current syncvm template creates an un-bootable config. The old template passed the flask label directly to xenm through extra-xenvm "flask-label". This worked for the xenvm-based system, but it broke with the XL conversion. "flask-label" is invalid in the XL config ("seclabel" should be used), so it throws an error about the legacy Python syntax.

The migration code hardcodes the syncvm_t flask label.  Alternate labels will be clobbered, but this doesn't seem like a realistic case to handle.

### CODE REVIEW

**Comment by jean-edouard** [comment]
LGTM. This probably makes sense in stable-8 too.
Merging Monday.

**Comment by eric-ch** [comment]
@jandryuk Can you PR against stable-8 as well please?

**Comment by jandryuk** [comment]
HVM NDVM introduced Migration 37 into master which is not present in stable-8.  How do people feel about skipping Migration 37 in stable-8 to better keep stable-8 & master in sync for the time being?

**Comment by jean-edouard** [comment]
I vote for swapping them. (move HVM NDVM to 38 and have this PR be 37)

**Comment by eric-ch** [comment]
Will merge soon.

**Pull request merged**
