### PR TITLE
Fix shutdown/reboot behavior from sleep.

### PR DESCRIPTION
**Pull request by crogers1**
Vm/Actions.hs:
  -Add a function that checks to see if the PV driver xs watches
   are responding after resuming from S3. Shutdown and reboot
   commands attempt to see if the drivers are listening before writing
   the "control/shutdown" node.

OXT-354

Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by crogers1** [comment]
Linked to https://github.com/OpenXT/xc-windows/pull/29

This is better than the arbitrary sleep I had proposed before.  I really wish I had the [RegisterResumeSuspendNotification](https://msdn.microsoft.com/en-us/library/windows/desktop/jj613321%28v=vs.85%29.aspx) function, but it's only available in Windows 8.  Instead, wait until the pv drivers respond by deleting the "control/awake" node, signalling they are in a state where they can fire off a xenstore-watch callback, and therefore able to issue a shutdown command when the "control/shutdown" node is written when calling shutdownVm or rebootVm.

**Comment by jean-edouard** [comment]
Isn't this sleeping 10 times 1 seconds instead of 2 times 5 seconds in https://github.com/OpenXT/manager/pull/23? :)

**Comment by crogers1** [comment]
#23 was a dumb sleep.  This is a timeout.  There are timeouts all over the toolstack, both in xenmgr and xenvm.  I'm trying to create an event to key off of (ie, waiting for the control/awake node to disappear, before sending the shutdown command) since acpi state change event doesn't work.

I haven't had time to look at Ross' code yet, which might provide a better event to key off of.

**Comment by rossphilipson** [comment]
Closing for now.

**Pull request closed without merging**
