### PR TITLE
If there's no state node, don't fire a shutdown

### PR DESCRIPTION
**Pull request by crogers1**
event.

OXT-973

Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by crogers1** [comment]
This is in support of @jean-edouard  fix for vwifs.

https://github.com/OpenXT/manager/pull/64

**Comment by jean-edouard** [comment]
+1, merge-able separately, without this fix network-daemon ends up with a rogue socket to network-slave.

**Comment by richpersaud** [comment]
Please reference a JIRA ticket that links related PRs, documenting the problem and solution.

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/689

**Comment by jean-edouard** [comment]
LGTM, fixed, merging soon.

**Pull request merged**
