### PR TITLE
STABLE-8: Domain reboot fix

### PR DESCRIPTION
**Pull request by crogers1**
OXT-1299

### CODE REVIEW

**Comment by eric-ch** [comment]
Building [$1508](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1508)

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1525

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1534

**Comment by jean-edouard** [comment]
Merging soon.

**Pull request merged**
