### PR TITLE
upgrade-db: add XL migration script

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-915
OXT-1059
OXT-1088

Signed-off-by: Jed <lejosnej@ainfosec.com>
Signed-off-by: Troy Crosley <crosleyt@ainfosec.com>

### CODE REVIEW

**Comment by eric-ch** [comment]
Build [842](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/842)

**Comment by crogers1** [comment]
Installed a 6.0.1 build, created a vm, upgraded to build 842, booted same vm without xl issues.  Recommend merging.

**Comment by eric-ch** [comment]
Tested as well, with upgrade from 6.0.1 (renamed 7.0.0 to pass the test for the occasion).
LGTM, +1.

**Comment by rossphilipson** [comment]
Looks like this and the stable-7 one are tested and ready to go in. Merging soon.

**Pull request merged**
