### PR TITLE
xenmgr: use readProcessOrDie to avoid fd leaks

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-1193

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by eric-ch** [comment]
Building [1131](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1131)

**Comment by crogers1** [comment]
I wasn't aware that readProcess leaked any fds.

**Comment by jean-edouard** [comment]
`readProcess` is a wrapper around `createProcess`, which doesn't close fds before exec-ing unless `{close_fds = True}`.

**Comment by dpsmith** [comment]
What is the status on this PR?

**Comment by eric-ch** [comment]
@dpsmith my bad I overlooked it after the community call last week, testing now.

Code LGTM (like @jean-edouard said, it is documented behavior in the [documentation](https://hackage.haskell.org/package/process-1.6.1.0/docs/System-Process.html))

**Pull request merged**
