### PR TITLE
[xenmgr] Default to hvm ndvm for x64

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Chris <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by rneilturner** [comment]
We will need to resolve the PV NDVM issues for x64 regardless on whether we move to an HVM NDVM.

**Comment by stacktrust** [comment]
Please create a JIRA ticket for 64-bit PV NDVM issue.

Please create a JIRA ticket on the motivation and consequences of changing the default NDVM guest type.

**Comment by stacktrust** [comment]
Ticket for default HVM NDVM: https://openxt.atlassian.net/browse/OXT-1634

**Comment by stacktrust** [comment]
@crogers1 This security-related PR has been open for a few months.  Can it be merged soon for stable-9 testing?

**Comment by eric-ch** [comment]
Build [$6653](http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6653)

**Comment by eric-ch** [comment]
Will merge soon.

**Pull request merged**
