### PR TITLE
[xenmgr] Send atapi args through xl disk spec

### PR DESCRIPTION
**Pull request by crogers1**
OXT-1017

Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by crogers1** [comment]
This is half of what's needed for oxt-1017, don't bother testing till the PR against libxl to consume these new args is posted.

**Comment by jean-edouard** [comment]
Here's the other half: https://github.com/OpenXT/xenclient-oe/pull/588

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/738

**Comment by rossphilipson** [comment]
Tested working, will merge soon.

**Pull request merged**
