### PR TITLE
templates: refresh

### PR DESCRIPTION
**Pull request by jean-edouard**
- Add Windows 10 to the UI list
- Add 32MB of RAM per stubdomain
- Give 2048MB of RAM by default to Windows 7+ VMs (which matches Microsoft requirements)
- Remove obsolete viptables rules

OXT-543
OXT-556

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://158.69.127.133:8020/builders/openxt-custom/builds/85

**Comment by rossphilipson** [comment]
@jean-edouard I agree that maybe a small bump to stubdom memory is in order since we have made a big kernel version jump forward. On the other hand, looking through our defconfig for stubbies, it looks loaded with things we don't need. How about we just bump 16M and I will put a ticket in to fix up the stubby defconfig?

**Comment by jean-edouard** [comment]
Ack, fixing PR now.

**Comment by rossphilipson** [comment]
Putting in ticket and I will test this...

**Comment by jean-edouard** [comment]
Fixed.

**Comment by rossphilipson** [comment]
Ticket to look at defconfig for stubbies:
https://openxt.atlassian.net/browse/OXT-603

**Comment by rossphilipson** [comment]
Tested, don't see any issues or errors (that were not there before anyway). Will merge soon.

**Pull request merged**
