### PR TITLE
xenmgr: xl.cfg: use the qemu path VM property

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Depends on https://github.com/OpenXT/dm-agent/pull/13 and https://github.com/OpenXT/xenclient-oe/pull/857

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1452

**Comment by eric-ch** [comment]
Can you please PR against stable-8?

**Comment by jean-edouard** [comment]
[Here](https://github.com/OpenXT/manager/pull/112) [you](https://github.com/OpenXT/dm-agent/pull/14) [go](https://github.com/OpenXT/xenclient-oe/pull/859)

**Comment by eric-ch** [comment]
Will merge soon.

**Pull request merged**
