### PR TITLE
STABLE-8: Fix XL syntax for raw disks

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>
(cherry picked from commit d6e1121b05289180db0e06d8f629938a425aa04b)
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by eric-ch** [comment]
Will merge soon.

**Comment by rneilturner** [comment]
Although not blocking this PR, there is still an issue with using raw disks inside of a stubdom. Also, our use case doesn't allow for non-stubdoms so we never tested the raw disk access outside of a stubdom. We did validate this functionality worked with stubdom's turned on for stable-6. We will be investigating further what is needed for raw disk access on stable-8 with stubdom support.

**Comment by eric-ch** [comment]
@rneilturner Interesting. I tried following [OXT-1356](https://openxt.atlassian.net/browse/OXT-1356) verification steps, which only check if the toolstack passes the guest starts and can detect the disk, but not its usage. What is the issue you are seeing?

**Comment by rneilturner** [comment]
I will get the logs tomorrow from the test engineer. I believe it got as far as booting the stubdom and then received an error. He spent most of the afternoon validating stable-6 which worked fine. I don't think he was able to get very far with the triage.

**Comment by eric-ch** [comment]
@rneilturner Any development on that?

**Comment by deepin125** [comment]
This is what I was seeing when attempting to do the disk pass through.
[failure.txt](https://github.com/OpenXT/manager/files/2146792/failure.txt)

**Comment by eric-ch** [comment]
Build: [$1590](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1590)

**Comment by eric-ch** [comment]
@deepin125 Build: [$1590](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1590) repro the issue consistently for VMs with stub-domain. I'll comment the ticket so we can merge this first and investigate the stub-domain case.

**Pull request merged**
