### PR TITLE
Handle the default stubdom memory and cmdline outside of the VM configs

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-730

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by eric-ch** [comment]
LGTM, +1.

**Comment by eric-ch** [comment]
Will merge soon.

**Comment by rossphilipson** [comment]
@eric-ch are you ok with losing the ability to change the stubdom command line (or maybe I am missing something)?

@jean-edouard should this go in stable 6 too?

**Comment by eric-ch** [comment]
@rossphilipson You can still change it using the configuration file. It just now uses the default value hardcoded in xenmgr & xenvm by default. Since this is a value aimed mostly for testing new stubdoms, it seems fine to me.

**Comment by rossphilipson** [comment]
@eric-ch ack that smack

**Pull request merged**
