### PR TITLE
Allow Stubdomain configuration of a given VM through the toolstack

### PR DESCRIPTION
**Pull request by eric-ch**
Add logic to xenmgr for:
 - stubdom-cmdline:
   * cmdline to be appended to the stubdomain's default cmdline.
     Can be set from the VM configuration file or through DBus
 - stubdom-memory:
   * Memory given to the stubdomain, in megabytes.
     Can be set from the VM configuration file or through DBus

OXT-332

See related PR in:
- xenclient-oe.git
- toolstack.git
- idl.git

### CODE REVIEW

**Comment by crogers1** [comment]
+1, looks good to me!

**Comment by jean-edouard** [comment]
+1

**Comment by eric-ch** [comment]
Defines the "default" stub-domain kernel command line in the VM configuration templates. Also add stubdom-memory argument to make it more visible.

**Comment by cjp256** [comment]
@eric-ch I don't see it, but perhaps I am missing something. Is there a default specified in the toolstack if unspecified?  I'm concerned about VMs that will likely break after an upgrade.

**Comment by eric-ch** [comment]
@cjp256 No I removed the default in https://github.com/eric-ch/toolstack/commit/bd0d4579282bedc15711f1ed2fd535d01a31c478, which is not good for existing VMs at the time of the upgrade. We might as well keep the default and let the configuration override it.

**Comment by cjp256** [comment]
@eric-ch : sounds like a good idea.

**Comment by eric-ch** [comment]
@cjp256 https://github.com/eric-ch/toolstack/commit/57d13ae452d4d78185a25b746544cbbf1462d188 default value is back.

**Pull request merged**
