### PR TITLE
Add migration script to disable cdrom autolock

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-635

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by rossphilipson** [comment]
Things seem to work fine with non-USB CD devices. No auto assignments happens but explicit assign and un-assign work. USB CD devices do still get auto assigned to the VM in focus. Not sure what the intended behavior should be...

**Comment by jean-edouard** [comment]
Yes, that's expected, I'll make a PR to prevent auto-assignment of USB optical devices to make things more obvious.

**Comment by rossphilipson** [comment]
The device UI seems to be broken or at least got broken when it tried to deal with a USB CD device. It is stuck in a mode where it cannot assign devices. I have no idea what is wrong - I will make a separate ticket for that.

Given the problems above and that this was originally about CD assignment and not USB assignment (which works fine), I would argue for leaving USB assignment alone for the moment. The issue this PR addresses was working before I started fooling with USB devices so I am going to merge the original PR soon.

**Comment by rossphilipson** [comment]
I think that changing USB assignment behaviors is not really part of this ticket and should have its own (and possibly an RFC on the ML).

**Pull request merged**
