### PR TITLE
xenmgr: handle empty power management actions as "nothing"

### PR DESCRIPTION
**Pull request by jean-edouard**
and log wrong values

OXT-866

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by pearsonk** [comment]
This fixes the "" handling causing problems, but would this cause similar problems on bad or erroneous PM values with the error() call? I think it should be logged, but configuration errors in the PM policy shouldn't have the power to cause such crippling in the system. Ideal behavior would be that it logs an unknown/inappropriate value but takes the "do nothing" action.

I'm haven't looked deeply in the code, so ignore this post if my assumptions are wrong.

**Comment by jean-edouard** [comment]
@pearsonk this is a good idea, but I'd need some help to figure out how to log an error *and* keep going with "nothing"...

**Comment by crogers1** [comment]
Unfortunately, this function isn't being used in the IO context, so the only way to perform IO (ie logging the error) on demand like that is to use _unsafePerformIO_ which isn't recommended, hence the function name.

I woudn't use _error_ at all, since it's supposed to stop execution.  Just have invalid PM action strings evaluate to ActionNothing.

**Comment by jean-edouard** [comment]
Silently ignoring bad values doesn't sound great to me...
It could hide issues, like if the UI gets rewritten with a typo in a pm state or something.
Haskell is rea^W^W^W

**Comment by crogers1** [comment]
With some finesse you could probably get it to log an error, but it would be a larger diff.  If you want I can spend a little time tomorrow looking at it.

**Comment by jean-edouard** [comment]
Replaced by https://github.com/OpenXT/manager/pull/49

**Pull request closed without merging**
