### PR TITLE
[xenmgr] Gpu pci class id masking

### PR DESCRIPTION
**Pull request by crogers1**
OXT-962

Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by crogers1** [comment]
After discussing alternate approaches with @jean-edouard, this is the one we settled on.  By only calling predMask when looking for gpu devices, we match on all devices of 0x3XX, thereby solving the original problem without code duplication.  We maintain the original behavior for other device types, so distinctions between device classes such as wired and wireless nics are observed.

**Comment by pearsonk** [comment]
I like the approach and reusability of this PR. Easy to understand, for Haskell.

**Comment by jean-edouard** [comment]
+1, closing mines

**Comment by rossphilipson** [comment]
Merging soon since it is identical to https://github.com/OpenXT/manager/pull/63 and that was tested.

**Pull request merged**
