### PR TITLE
Add  AHCI support (Qemu SATA disk emulation)

### PR DESCRIPTION
**Pull request by mahantesh-ais**
OXT-1123

### CODE REVIEW

**Comment by mahantesh-ais** [comment]
To be merged along with:
https://github.com/OpenXT/xenclient-oe/pull/1098
https://github.com/OpenXT/idl/pull/32

**Comment by pearsonk** [comment]
Slight nitpick of naming, but why the selection of "hdtype"? This seems to imply hard drive, but the interface for SATA is beyond hard drives (ISOs). Would something more like "bustype" be a better representation?

**Comment by mahantesh-ais** [comment]
I agree, but I carried the same name provided by xen(xl) config,
which can be seen here: http://xenbits.xen.org/docs/4.11-testing/man/xl.cfg.5.html

**Comment by pearsonk** [comment]
Makes sense to me. Again, was just a nitpick. Thanks for taking this on, I've been wondering why we were only using IDE emulation for a while, especially with the limitations of VHDs, default virtual ISO, and ATAPI-pt.

**Comment by mahantesh-ais** [comment]
Built here:
http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1896

**Comment by jean-edouard** [comment]
Merging soon.

**Pull request merged**
