### PR TITLE
xenmgr: use readProcessOrDie to avoid fd leaks

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-1193

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by eric-ch** [comment]
Build [#1109](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1109).
LGTM, will merge soon.

**Comment by eric-ch** [comment]
Rebased on master to avoid "merge" commit in the history. Building [1121](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1121).

**Comment by dpsmith** [comment]
Did build 1128 checkout? Possible to get a stable-7 version?

**Comment by eric-ch** [comment]
@dpsmith I just kicked 1128, the previous build failed to fetch a tarball.

**Comment by jean-edouard** [comment]
Replaced by https://github.com/OpenXT/manager/pull/103

**Pull request closed without merging**
