### PR TITLE
OXT-1538: Re-work partition mounting.

### PR DESCRIPTION
**Pull request by jandryuk**
This PR re-works mounting disk images to address the intermittent start failure of NDVM and other VMs.  A kernel change in 4.19 introduced an intermittent failure when using an offset with mount.  Under the hood, mount creates a loopdev when using an offset.

The old xenmgr code to mount a partition created a tapdev and then used mount -o offset= to mount a partition.  The new way, creates the tapdev, creates a loopdev with partitions, and then mounts the loopdev partition.  This side-steps the offset issue and lets the mounting succeed.

Using loopdev partition scanning is a little nicer in that we don't have to run fdisk and parse that output.  We just let the kernel do its thing and use the created device nodes.

### CODE REVIEW

**Comment by eric-ch** [comment]
Building [$6530](http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6530)

**Comment by eric-ch** [comment]
The ticket does not mention "Fix version: 9.0.0", but I assume this is stable-9 material @crogers1 ?

**Comment by jandryuk** [comment]
Thanks, @crogers1 .  After pushing the PR, I have noticed this AVC:

> kernel:[ 1708.372665] audit: type=1400 audit(1556132167.469:7): avc:  denied  { read } for  pid=12068 comm="mount" name="loop0p1" dev="devtmpfs" ino=97997 scontext=system_u:system_r:mount_t:s0-s0:c0.c1023 tcontext=system_u:object_r:device_t:s0 tclass=blk_file permissive=0

This is weird since `/dev/loop.*` should be labeled `fixed_disk_device_t` and they do seem to be when I `ls /dev/loop*`.  Could there be a race between the node appearing and udev re-labeling it?

**Comment by eric-ch** [comment]
@jandryuk Missed it on the serial output upon first test, this is not the only "new" output:

At NDVM creation:
```
[   88.126871] block tda: sector-size: 512/512+0 capacity: 581632 discard: 0+0 flush: 0x4022440
[   88.176133]  loop0: p1 p2
[   88.180202] audit: type=1400 audit(1556134925.729:4): avc:  denied  { read } for  pid=1359 comm="mount" name="loop0p1" dev="devtmpfs" ino=13947 scontext=sy
stem_u:system_r:mount_t:s0-s0:c0.c1023 tcontext=system_u:object_r:device_t:s0 tclass=blk_file permissive=0
[   88.525129] __loop_clr_fd: partition scan of loop0 failed (rc=-22)
```

At UIVM creation:
```
[   96.983772] block tdc: sector-size: 512/512+0 capacity: 729088 discard: 0+0 flush: 0x4022440
[   97.042330] EXT4-fs (loop0): mounting ext3 file system using the ext4 subsystem
[   97.042749] EXT4-fs (loop0): mounted filesystem with ordered data mode. Opts: (null)
[   97.234932] __loop_clr_fd: partition scan of loop0 failed (rc=-22)
```

**Comment by jandryuk** [comment]
`  loop0: p1 p2` is expected now that we are using partscan.

I can get some of the `__loop_clr_fd: partition scan of loop0 failed (rc=-22)` messages to go away by only passing "--partscan" when we are expecting a partition.  However, I still see it when we actually have partitions.  The /dev/loop0p1 nodes aren't getting cleaned up, so something must be wrong in the kernel, I guess?

**Comment by eric-ch** [comment]
@jandryuk Yes, I was more worried about the `__loop_clr_fd` message. Could be related to https://lkml.org/lkml/2019/2/21/736. Definitely minor though.

**Comment by jandryuk** [comment]
Yes, that may be it.  And the change is included in a newer 4.19.y release.

**Comment by jandryuk** [comment]
With the 4.19.y equivalent of https://lkml.org/lkml/2019/2/21/736, the device nodes are cleaned up properly.  The kernel still has:
`kernel:[ 3402.297074] __loop_clr_fd: partition scan of loop0 failed (rc=0)`
Linux master has a change to silence those when there is no error (rc=0).

We we'll quiet the message when linux is upreved.

**Comment by crogers1** [comment]
@eric-ch yes I will approve the stable-9 PR as well

**Comment by jandryuk** [comment]
I added this commit: https://github.com/OpenXT/manager/pull/139/commits/13372d5b0d126821d7d978b03a677f3e2f2d30fe which reduces the __loop_clr_fd messages a little bit by skipping partscan when not needed.

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6533

**Comment by jean-edouard** [comment]
Still getting the AVC:
```
Apr 29 18:20:31.440813 kernel:[   11.036123] audit: type=1400 audit(1556562031.429:4): avc:  denied  { read } for  pid=1200 comm="mount" name="loop0p1" dev="devtmpfs" ino=14478 scontext=system_u:system_r:mount_t:s0-s0:c0.c1023 tcontext=system_u:object_r:device_t:s0 tclass=blk_file permissive=0
```

**Comment by jandryuk** [comment]
That AVC is weird since it seems like `/dev/loop0p1` is mislabeled `device_t` when storage.fc specifies `fixed_disk_device_t`.  It may be a race that /dev/loop0p1 is created by the kernel & devtmpfs which then needs to be relabeled by udev to `fixed_disk_device_t`.

I haven't seen an actual mount failure.  I could add a `dontaudit` to silence the avc.

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6545

**Comment by jean-edouard** [comment]
LGTM, merging soon.

**Comment by jean-edouard** [comment]
LGTM, merging soon.

**Pull request merged**
