### PR TITLE
[xenmgr] Send new hard shutdown flag if guest

### PR DESCRIPTION
**Pull request by crogers1**
isn't listening for acpi signals. Also write hvm-shutdown node
  that qemu acpi code is watching.

  OXT-1091

Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by eric-ch** [comment]
Build [835](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/835)

**Comment by eric-ch** [comment]
That does not seem to work.
Using [build 835](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/835):
- booting to debian-7.8.0-i386-netinst.iso,
- then switch back to UIVM and clic "Shutdown"

will not affect the VM, but the UI will have the spinner and report the VM is "stopping").
The xenstore node ```/local/domain/<domid>/control/hvm-powerbutton-enable``` is not around:
```
root@xenclient-dom0:/storage/isos# xenstore-ls -pf /local/domain/5/control
/local/domain/5/control/shutdown = ""   (n5)
/local/domain/5/control/platform-feature-multiprocessor-suspend = "1"   (n5)
/local/domain/5/control/platform-feature-xs_reset_watches = "1"   (n5)
```
I tried both xl commands invoked in the changes:
```
root@xenclient-dom0:/storage/isos# xl shutdown -c 5
option `c' not supported.
Shutting down domain 5
PV control interface not available: external graceful shutdown not possible.
Use "-F" to fallback to ACPI power event.
shutdown failed (rc=-10)
```
And
```root@xenclient-dom0:/storage/isos# xl shutdown -F 5
Shutting down domain 5
PV control interface not available: sending ACPI power button event.
```
With ```xl shutdown -F``` not doing anything in the end.

**Comment by crogers1** [comment]
It sounds like build 835 is missing the libxl commit in xenclient-oe.

**Comment by crogers1** [comment]
https://github.com/OpenXT/xenclient-oe/pull/627

**Comment by eric-ch** [comment]
Indeed, new build incoming, I missed the second PR.

**Comment by eric-ch** [comment]
Build [843](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/843).
Previously mentioned test now succeed with the build including https://github.com/OpenXT/xenclient-oe/pull/627.
LGTM, will merge soon.

**Pull request merged**
