### PR TITLE
[xenmgr] Add initrd to xl config

### PR DESCRIPTION
**Pull request by tsirakisn**
Putting this up while I sort out some issues with my build tree, note this is untested for now. Once I get xenmgr building I will test this change out.

OXT-1287

### CODE REVIEW

**Comment by tsirakisn** [comment]
Update: initrd showing properly in xl config. PR ready for merge.

**Comment by tsirakisn** [comment]
Fixed, merge with: https://github.com/OpenXT/xenclient-oe/pull/1112

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6472

**Comment by jean-edouard** [comment]
LGTM, merging soon.

**Pull request merged**
