### PR TITLE
STABLE-9: OXT-1596: [xenmgr] Error if VMs disk paths are bad

### PR DESCRIPTION
**Pull request by crogers1**
When a the phys-path to a VM's disk is bad, the VM can be stuck
  for a long time in an invalid state without a visual indication
  something is wrong. This will also catch the case where a phys-path
  is empty or the actual disk was deleted or moved. Xenmgr will throw
  an error which can be seen in the UI and the VM state will be
  reset to a sane state of Shutdown.

  OXT-1596

Signed-off-by: Chris <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6546

**Comment by jean-edouard** [comment]
Works great, one minor comment though, the message says "bad path" twice...
Looks like: "Bad Physical Path for disk 0 bad path /storage/isos/nulll.iso"
How about something like: "Bad Physical Path for disk 0 (/storage/isos/nulll.iso)"
Thanks

**Comment by crogers1** [comment]
Sure I can update that

**Comment by jean-edouard** [comment]
Merging soon.

**Pull request merged**
