### PR TITLE
[xenmgr] Fix Power Control support

### PR DESCRIPTION
**Pull request by crogers1**
OXT-942

Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by rossphilipson** [comment]
@crogers1 Is the test for this fix just test Win10 guest S3?

**Comment by crogers1** [comment]
Set the Power Control option in the VM details to "affects guest AND host".  The following cases should be tested:
1. Shutdown guest.  Expected: Host shuts down too
2. Reboot guest.  Expected: Guest reboots normally, no host shutdown
3. S3 guest: Expected: Host S3.
  3a. Note that Host S3 seems to be broken on various hardware. On the Broadwell NUC I tested on, 2 iterations of Host S3/Resume caused a platform lockup.  The behavior itself seems inconsistent across platforms.

In the xenmgr code you'll see a hibernate case, but Host hibernate just performs acpi shutdown (S5), not S4, so that path seems unsupported to me.

**Comment by rossphilipson** [comment]
Built here:
http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/829
Testing now

**Comment by rossphilipson** [comment]
From test instructions above:
1. Passed
2. Passed
3. Passed for the purposes of this ticket. The system I used died on resume with a panic related to the APIC but that is a separate issue.

I am hoping to get a code review on this but otherwise LGTM.

**Comment by rossphilipson** [comment]
Thanks for the review. Merging soon.

**Pull request merged**
