### PR TITLE
STABLE-9: OXT-1538: Re-work partition mounting

### PR DESCRIPTION
**Pull request by jandryuk**
This is the Stable-9 version of https://github.com/OpenXT/manager/pull/139

This PR re-works mounting disk images to address the intermittent start failure of NDVM and other VMs. A kernel change in 4.19 introduced an intermittent failure when using an offset with mount. Under the hood, mount creates a loopdev when using an offset.

The old xenmgr code to mount a partition created a tapdev and then used mount -o offset= to mount a partition. The new way, creates the tapdev, creates a loopdev with partitions, and then mounts the loopdev partition. This side-steps the offset issue and lets the mounting succeed.

Using loopdev partition scanning is a little nicer in that we don't have to run fdisk and parse that output. We just let the kernel do its thing and use the created device nodes.

### CODE REVIEW

**Comment by eric-ch** [comment]
Building: [$6531](http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6531)

**Comment by jean-edouard** [comment]
Merging soon.

**Comment by jean-edouard** [comment]
@jandryuk, please align with master PR.

**Comment by jandryuk** [comment]
Updated.  Thanks for checking and the reminder.

**Comment by jean-edouard** [comment]
Merging soon.

**Pull request merged**
