### PR TITLE
Fix XL syntax for raw disks

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by rneilturner** [comment]
Building on downstream now, will have results from our testing by tomorrow.

**Comment by eric-ch** [comment]
Ticket: [OXT-1356](https://openxt.atlassian.net/browse/OXT-1356)

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1570

**Comment by eric-ch** [comment]
Will merge soon.

**Pull request merged**
