### PR TITLE
OXT-1647: templates: Make UIVM default to PVH.

### PR DESCRIPTION
**Pull request by eric-ch**
Change `virt-type` from `pv` to `pvh`.

### CODE REVIEW

**Comment by eric-ch** [comment]
### Required PRs:

- https://github.com/OpenXT/xenclient-oe/pull/1219
- https://github.com/OpenXT/input/pull/34
- https://github.com/OpenXT/surfman/pull/28

### Optional:
- https://github.com/OpenXT/manager/pull/170 (Default UIVM to pvh).

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6668

**Comment by jean-edouard** [comment]
LGTM but did you test upgrade?

**Comment by eric-ch** [comment]
@jean-edouard embarrassingly not... Will do so. If someone else does, my main concern would be that the updated installation did not switch to PVH. The UIVM kernel still has the full PV support, so it will boot fine as PV.

**Comment by jean-edouard** [comment]
Just tested it, works fine, merging soon.

**Pull request merged**
