### PR TITLE
OXT-1327: HVM NDVM

### PR DESCRIPTION
**Pull request by jandryuk**
Allow selecting between PV and HVM mode for NDVM.

xenmgr looks for /usr/share/xenmgr-1.0/templates/default/service-* to determine the default service VM templates.  xenmgr is modified to choose between service-ndvm-pv and service-ndvm-hvm at runtime.

I'm not happy with c40fc5c2bcc72cff71264765f1c8cb9fd4fe6fe1.  I wanted to call getNdvmMode within enumServiceVmTags , but my attempts all lead to type errors.  I think it might be from trying to nest liftRpc within the liftRpc in xenmgr/Main.hs.  I'm not sure how to get around that.  Suggestions welcome!

Also add support for display=nogfx to disable graphics.  PartTable needed a fix so xenmgr can extract the kernel from the partitioned disk in PV mode.

### CODE REVIEW

**Comment by crogers1** [comment]
@jandryuk I'm going to give this a look tomorrow.

**Comment by crogers1** [comment]
So to answer your question about getNdvmMode, you can't call it inside enumVmServiceTags because getNdvmMode returns ```Rpc String``` and enumVmServiceTags returns ```IO [String]```.  You can't lift an Rpc -> IO because the definition of the IO Monad doesn't understand what an Rpc is.  But if you look in the class definition of Rpc, you'll see it extends MonadIO, and the definition of liftRpc has an instance of MonadIO.

If you wanted to call getNdvmMode within enum, you'd have to change the return type of enumVmServiceTags to Rpc String and ```liftIO``` the ```filesInDir```, but then you'd have to make changes wherever enumVmServiceTags is called to be happy with your type change.

I looked at the rest of the commits, the changes look fine to me.

**Comment by jandryuk** [comment]
@crogers1 thanks for the response.  Changing `enumVmServiceTags` to `Rpc String` isn't that bad, if I remove the unused enumServiceVmTemplates.

This is what I originally wanted:
```
-enumServiceVmTags :: String -> IO [String]
-enumServiceVmTags ndvm_mode =
+enumServiceVmTags :: IO [String]
+enumServiceVmTags =
     do template_dir <- getTemplateDir
        tags <- catMaybes . map get_tag <$> filesInDir template_dir
        info $ "ndvm mode " ++ ndvm_mode ++ " tags: " ++ ( intercalate " " tags )
        return $ filter ( filt_ndvm ndvm_mode ) tags
     where
+      ndvm_mode = liftRpc getNdvmMode
       get_tag f = case takeBaseName f of
                     's':'e':'r':'v':'i':'c':'e':'-':tag -> Just tag
                     _ -> Nothing
```
but it throws:
```
Vm/Templates.hs:138:30:
    Couldn't match expected type `Char' against inferred type `[Char]'
      Expected type: [Char]
      Inferred type: [String]
    In the first argument of `(++)', namely `ndvm_mode'
    In the second argument of `(++)', namely
        `ndvm_mode ++ " tags: " ++ (intercalate " " tags)'
```
Your explanation is much more informative :).

**Comment by jandryuk** [comment]
@crogers1 your first response pointed me in the right direction, and I got it working.  Thank you.  My previous comment was to show the unhelpful and confusing message I received from ghc when I first tackled this change.

**Comment by crogers1** [comment]
@jandryuk Awesome!  Glad I could help :)

**Comment by jandryuk** [comment]
I re-pushed with this new commit: https://github.com/OpenXT/manager/pull/116/commits/f87cfe1dd4105084b1d95c7fe5000437ce6c8345 removing `enumServiceVmTemplates`
and this commit https://github.com/OpenXT/manager/pull/116/commits/8e3a80b9b8fb08727b004068d29935be0e36c4cb changed per @crogers1 suggestion

It was easier to just remove the unused `enumServiceVmTags` then deal with it becoming a mix of Rpc and IO Monads.

**Comment by crogers1** [comment]
Syntax and logic look good, recommend doing a build and testing for regressions

**Comment by eric-ch** [comment]
Build [$1558](http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1558)

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1562

**Comment by jean-edouard** [comment]
LGTM, merging soon.

**Pull request merged**
